#!/usr/bin/env bash
#  ███████╗██╗  ██╗████████╗███████╗██████╗ ███╗   ██╗ █████╗ ██╗
#  ██╔════╝╚██╗██╔╝╚══██╔══╝██╔════╝██╔══██╗████╗  ██║██╔══██╗██║
#  █████╗   ╚███╔╝    ██║   █████╗  ██████╔╝██╔██╗ ██║███████║██║
#  ██╔══╝   ██╔██╗    ██║   ██╔══╝  ██╔══██╗██║╚██╗██║██╔══██║██║
#  ███████╗██╔╝ ██╗   ██║   ███████╗██║  ██║██║ ╚████║██║  ██║███████╗
#  ╚══════╝╚═╝  ╚═╝   ╚═╝   ╚══════╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝╚══════╝
#
#              ██████╗ ██╗   ██╗██╗     ███████╗███████╗
#              ██╔══██╗██║   ██║██║     ██╔════╝██╔════╝
#              ██████╔╝██║   ██║██║     █████╗  ███████╗
#              ██╔══██╗██║   ██║██║     ██╔══╝  ╚════██║
#              ██║  ██║╚██████╔╝███████╗███████╗███████║
#              ╚═╝  ╚═╝ ╚═════╝ ╚══════╝╚══════╝╚══════╝
#	[Author] : gh0stzk
#	 [Url]   : https://github.com/gh0stzk/dotfiles
#

wid=$1
class=$2
instance=$3
consequences=$4

result() {
    eval "$consequences"
    [ "$state" ] || echo "$1"
}

case "$class" in
    FloaTerm)
		result "state=floating center=on rectangle=842x495+0+0"
        ;;
    Updating)
		result "state=floating sticky=on center=on rectangle=842x495+0+0"
        ;;
	Scratch)
		result "state=floating focus=on sticky=on"
		;;
	RiceEditor)
		result "state=floating focus=on center=on"
		;;
    mpv)
		result "state=floating focus=on center=on rectangle=723x407+0+0"
        ;;
	FullScreen)
		result "state=fullscreen"
		;;
    TelegramDesktop)
        result "desktop=^4 follow=on"
        ;;
    Pavucontrol)
        result "state=floating center=on"
        ;;
    Thunar)
        result "desktop=^2 follow=on"
        ;;
    Geany)
        result "desktop=^4 follow=on"
        ;;
    firefox|Navigator)
        result "desktop=^3 follow=on"
        ;;
    vesktop)
        result "desktop=^3 follow=on"
        ;;
    Vivaldi-stable)
        result "desktop=^5 follow=on"
        ;;
    Brave-browser)
        result "desktop=^5 follow=on"
        ;;
    FreeTube)
        result "desktop=^6 follow=on"
        ;;
	spotify-tray)
		result "state=floating follow=on rectangle=1050x685+0+0 center=on"
		;;
	Spotify)
		result "state=floating follow=on rectangle=1050x685+0+0 center=on"
		;;
	qpwgraph)
		result "state=floating follow=on rectangle=1240x900+0+0 center=on"
		;;
	Lxappearance)
		result "state=floating follow=on rectangle=1240x900+0+0 center=on"
		;;
	Nwg-look)
		result "state=floating follow=on rectangle=1240x900+0+0 center=on"
		;;
	Nvidia-settings)
		result "state=floating follow=on center=on"
		;;
	Viewnior)
		result "state=floating focus=on center=on"
		;;
	TelegramDesktop)
		result "state=floating focus=on center=on"
		;;
	Fileman)
		result "desktop=^2 follow=on"
		;;
	screencast)
		result "state=floating focus=on center=on rectangle=849x477+0+0"
		;;
	Galculator)
		result "state=floating focus=on center=on"
		;;
	Virt-manager)
		result "state=floating desktop=^5 follow=on center=on"
		;;
	gnome-network-displays)
		result "state=floating focus=on center=on"
		;;
esac

case "$instance" in
    Toolkit)
        result "state=floating sticky=on rectangle=500x290+1054+593"
        ;;
	YaziTerm)
		result "state=floating center=on rectangle=900x342+0+0"
		;;
	MusicTerm)
		result "state=floating center=on rectangle=656x343+0+0"
		;;
	FetchTerm)
		result "state=floating center=on rectangle=369x601+0+0"
		;;
esac
