#################
### AUTOSTART ###
#################

# exec-once = $terminal
exec-once = nm-applet &
exec-once = waybar
exec-once = /usr/lib/pam_kwallet_init

# Start apps
exec-once = sleep 3 && keepassxc
exec-once = sleep 3 && nextcloud
exec-once = sleep 4 && surfshark --hidden
exec-once = sleep 3 && blueman-applet

# Load cliphist history
exec-once = wl-paste --watch cliphist store

# Using hypridle to start hyprlock
exec-once = hypridle
