#!/usr/bin/env bash
#
#  ██████╗ ███████╗██████╗ ██╗    ██╗███╗   ███╗██████╗  ██████╗
#  ██╔══██╗██╔════╝██╔══██╗██║    ██║████╗ ████║██╔══██╗██╔════╝
#  ██████╔╝███████╗██████╔╝██║ █╗ ██║██╔████╔██║██████╔╝██║
#  ██╔══██╗╚════██║██╔═══╝ ██║███╗██║██║╚██╔╝██║██╔══██╗██║
#  ██████╔╝███████║██║     ╚███╔███╔╝██║ ╚═╝ ██║██║  ██║╚██████╗
#  ╚═════╝ ╚══════╝╚═╝      ╚══╝╚══╝ ╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝
#	Author	-	gh0stzk
#	Repo	-	https://github.com/gh0stzk/dotfiles
#	Copyright (C) 2021-2025 gh0stzk <z0mbi3.zk@protonmail.com>

# Set environment variables
export PATH="$HOME/.config/bspwm/src:$PATH"
export XDG_CURRENT_DESKTOP='bspwm'
## Fix java applications
export _JAVA_AWT_WM_NONREPARENTING=1

#  ╦ ╦╔═╗╦═╗╦╔═╔═╗╔═╗╔═╗╔═╗╔═╗╔═╗
#  ║║║║ ║╠╦╝╠╩╗╚═╗╠═╝╠═╣║  ║╣ ╚═╗
#  ╚╩╝╚═╝╩╚═╩ ╩╚═╝╩  ╩ ╩╚═╝╚═╝╚═╝

MonitorSetup

#  ╔╗ ╔═╗╔═╗╦ ╦╔╦╗  ╔═╗╔═╗╔╗╔╔═╗╦╔═╗
#  ╠╩╗╚═╗╠═╝║║║║║║  ║  ║ ║║║║╠╣ ║║ ╦
#  ╚═╝╚═╝╩  ╚╩╝╩ ╩  ╚═╝╚═╝╝╚╝╚  ╩╚═╝

bspc config external_rules_command "${HOME}"/.config/bspwm/src/ExternalRules

bspc config window_gap                5
bspc config split_ratio               0.51
bspc config single_monocle            true

bspc config automatic_scheme          longest_side
bspc config initial_polarity          second_child
bspc config removal_adjustment        true

bspc config focus_follows_pointer     true
bspc config pointer_follows_focus     false
bspc config pointer_follows_monitor   true
bspc config pointer_motion_interval   7
bspc config pointer_modifier          mod4
bspc config pointer_action1           move
bspc config pointer_action2           resize_side
bspc config pointer_action3           resize_corner

#  ╔═╗╦ ╦╔╦╗╔═╗╔═╗╔╦╗╔═╗╦═╗╔╦╗
#  ╠═╣║ ║ ║ ║ ║╚═╗ ║ ╠═╣╠╦╝ ║
#  ╩ ╩╚═╝ ╩ ╚═╝╚═╝ ╩ ╩ ╩╩╚═ ╩

# Set system vars for polybar
"$HOME"/.config/bspwm/src/SetSysVars

# Launch sxhkd daemon
pidof -q sxhkd || { sxhkd -c "${HOME}"/.config/bspwm/src/config/sxhkdrc & }

# Load current theme
"${HOME}"/.config/bspwm/src/Theme.sh

# Launch picom
pidof -q picom || { picom --config "${HOME}"/.config/bspwm/src/config/picom.conf & }

# Launch xsettingsd
pidof -q xsettings || { xsettingsd --config="${HOME}"/.config/bspwm/src/config/xsettingsd >/dev/null 2>&1 & }

# Launch eww daemon
pidof -q eww || { eww -c "${HOME}"/.config/bspwm/eww daemon & }

# Launch clipboard daemon
pidof -q clipcatd || { clipcatd & }

# Launch polkit
pidof -q polkit-gnome-authentication-agent-1 || { /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 & }

# Launch input gestures daemon
exec libinput-gestures-setup desktop autostart start &

# Launch hide mouse daemon
unclutter &

# Launch emacs daemon
/usr/bin/emacs --daemon &

## 1 > terminal (always open emacs on workspace-1)
declare -a term=(Emacs)
for i in ${term[@]}; do
   bspc rule -a $i state=tiled desktop='^1' follow=on focus=on; done

# Auto-start programs
start-nc.sh &
start-kp.sh &
start-ss.sh &

# End one time code
