#!/usr/bin/env bash
#   █████╗ ██████╗ ██████╗ ███████╗    ██╗      █████╗ ██╗   ██╗███╗   ██╗ ██████╗██╗  ██╗███████╗██████╗ 
#  ██╔══██╗██╔══██╗██╔══██╗██╔════╝    ██║     ██╔══██╗██║   ██║████╗  ██║██╔════╝██║  ██║██╔════╝██╔══██╗
#  ███████║██████╔╝██████╔╝███████╗    ██║     ███████║██║   ██║██╔██╗ ██║██║     ███████║█████╗  ██████╔╝
#  ██╔══██║██╔═══╝ ██╔═══╝ ╚════██║    ██║     ██╔══██║██║   ██║██║╚██╗██║██║     ██╔══██║██╔══╝  ██╔══██╗
#  ██║  ██║██║     ██║     ███████║    ███████╗██║  ██║╚██████╔╝██║ ╚████║╚██████╗██║  ██║███████╗██║  ██║
#  ╚═╝  ╚═╝╚═╝     ╚═╝     ╚══════╝    ╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═══╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

WIDGET_DIR="$HOME/.config/bspwm/eww"

	case "$1" in
		--menu)
			rofi -show drun -theme $HOME/.config/bspwm/scripts/Launcher.rasi
			;; 
		--terminal)
			Term --terminal
			;;
		--floating)
			Term --floating
			;;
		--update)
			Term --update 
			;;
		--checkupdates)
			Term --checkupdates
			;;
		--ranger)
			Term --ranger
			;;
		--nvim)
			Term --nvim
			;;
		--music)
			Term --music
			;;
		--fetch)
			Term --fetch
			;;
		--sysmon)
			Term --sysmon
			;;
		--nvtop)
			Term --nvtop
			;;
		--rangerfloat)
			Term --ranger-float
			;;
		# Apps
		--filemanager)
			thunar
			;;
		--browser)
			firefox
			;;
		--editor)
			geany
			;;
		--telegram)
			telegram-desktop
			;;
		--soundcontrol)
			pavucontrol
			;;
		--screencast)
			gnome-network-displays
			;;
		--whats)
			whatsdesk --disable-gpu
			;;
		--emacs-c)
			emacsclient -c -a "";;
		# Eww Widgets
		--powermenu)
			eww -c "$WIDGET_DIR" open --toggle powermenu
			;;
		--usercard)
			eww -c "$WIDGET_DIR" open --toggle launchermenu
			;;
		--player)
			eww -c "$WIDGET_DIR" open --toggle music
			;;
		--calendar)
			eww -c "$WIDGET_DIR" open --toggle date
			;;
		--netmanager)
			NetManagerDM
			;;
		*)
			echo "Opción no válida"
			;;
	esac
