#!/usr/bin/env bash

## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>

# bspwm directory
DIR="$HOME/.config/bspwm"

# rofi sudo askpass helper
export SUDO_ASKPASS="$DIR"/src/rofi_askpass

# execute the application
sudo -A $1
