#!/usr/bin/env bash

## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/.config/bspwm"
RASI="$DIR/src/rofi-themes/launcher.rasi"

# Run
rofi \
    -show drun \
	-kb-cancel Escape \
	-theme ${RASI}
#Super_L
