#!/usr/bin/env bash

## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
DIR="$HOME/.config/bspwm"
RASI="$DIR/src/rofi-themes/askpass.rasi"

# Rofi text dialog to get password
rofi -dmenu \
     -password \
     -i \
     -p "Root" \
     -theme ${RASI}
